gnustep/libs-base

Headers/GNUstepBase/GSBlocks.h, Headers/ObjectiveC2/objc/blocks_runtime.h, Source/GSBlocks.m, Source/ObjectiveC2/blocks_runtime.m
Make the Blocks API compatible with Apple LLVM.
=> Get compatible with Apple LLVM API

ChangeLog, Source/NSDateFormatter.m, configure, configure.ac
=> Decrease ICU version requirements to 49

Source/NSThread.m
This will be used on platforms without pthread_spin_lock(), e.g. Android targeting API level < 24.
The implementation lifted from [libobjc2’s spinlock.h](https://github.com/gnustep/libobjc2/blob/master/spinlock.h). Please let me know if this requires attribution and where it should go.
=> Added basic spinlock implementation using builtins.

Headers/Foundation/NSArray.h, Headers/Foundation/NSDictionary.h, Headers/Foundation/NSOrderedSet.h, Source/GSOrderedSet.m, Source/NSArray.m, Source/NSDictionary.m, Source/NSOrderedSet.m, Source/NSSet.m, Tests/base/NSOrderedSet/basic.m, Tests/base/NSOrderedSet/blocks.m
This change adds the NSOrderedSet and NSMutableOrderedSet class cluster to GNUstep.  All of the methods are present except those currently in Apple's beta.   Please review and let me know of any feedback you may have.
=> Add nsorderedset classcluster

Headers/Foundation/NSHashTable.h
This adds support for using generics with NSHashTable as on Apple platforms.
=> Added generics support to NSHashTable

Headers/Foundation/NSOperation.h, Source/NSOperation.m
Putting this in for review.  Still need to add tests to this branch, but I want Fred and others to look at it to see if there is any obvious miss.
=> NSBlockOperation changes

Headers/Foundation/NSSortDescriptor.h, Source/NSSortDescriptor.m
Added the ability to use a comparator the NSSortDescriptor.   Need to add tests for this class as well, but wanted to get it into review.
=> NSSortDescriptor branch

Headers/Foundation/MISSING, Headers/Foundation/NSFileManager.h, Headers/Foundation/NSPathUtilities.h, Source/NSFileManager.m
Add methods to NSFIleManager URLForDirectory:... enumeratorAtURL....
=> NSFileManager branch

Headers/Foundation/NSProgress.h, Source/GNUmakefile, Source/NSProgress.m
This branch contains an implementation of the NSProgress class.  This class allows for easy monitoring of progress for a given task and also allows the creation of a tree of dependent progress objects to monitor subtasks.
=> NSProgress branch

ChangeLog, Headers/GNUstepBase/GSIMap.h, Source/NSConcreteHashTable.m, Source/NSConcreteMapTable.m
when checking in enumerator.
* Source/NSConcreteHashTable.m,
* Source/NSConcreteMapTable.m: Revert part of the weak pointer change.
=> * Headers/GNUstepBase/GSIMap.h: Use GSI_MAP_NODE_IS_EMPTY macros

Source/NSURL.m, Tests/base/NSURL/components.m
I created a new pull request for Richards cleanup. For me it is fine to merge this as well.
=> fixups for setting/getting nil/empty query string values

Headers/Foundation/NSRunLoop.h, Headers/Foundation/NSURLConnection.h, Source/NSRunLoop.m, Source/NSURLConnection.m
=> Add methods from 10.5

ChangeLog, Headers/Foundation/NSURL.h, MISSING, Source/NSURL.m
- URLByAppendingPathComponent:isDirectory:
- isFileReferenceURL (always returns NO)
- fileReferenceURL
- filePathURL
Note that this is not an actual implementation of "file reference URLs" (I am not sure if there would be a way to support these in a cross-platform manner).
=> Add various NSURL methods.

Tools/plutil.1, Tools/plutil.m
Some is better than none. Let me see how much I can write...
=> plutil: Some documentation

ChangeLog, Headers/Foundation/NSFileHandle.h, MISSING, Source/NSFileHandle.m
* -fileHandleForReadingFromURL:error:
* -fileHandleForWritingToURL:error:
* -fileHandleForUpdatingURL:error:
Also use "instancetype" for all initializers.
=> Add NSFileHandle URL initializers.

ChangeLog, Headers/Foundation/NSNull.h, Tests/base/Functions/NSByteSwapping.m, configure, configure.ac
A couple more small fixes / tweak for building for Windows MSVC.
=> Windows MSVC fixes

Headers/Foundation/NSLock.h, Headers/Foundation/NSStream.h
=> Add missing GS_EXPORT_CLASS annotations.

Source/GSHTTPURLHandle.m
was failed, since its test read would leave the file handle with a read
in progress, invalidating further background reads. More recent versions
of Windows seem to handle the unix way.
=> The portable way to detect if a socket is reusable or has been closed

Headers/GNUstepBase/GSXML.h, Headers/GNUstepBase/NSString+GNUstepBase.h, Source/NSBundle.m, Source/NSString.m, Tests/base/NSJSONSerialization/tests00.m, Tests/base/NSLock/RecursiveLock.m, Tests/base/NSMethodSignature/general.m, Tests/base/NSNumber/test02.m, Tests/base/NSObject/initialize.m, Tests/base/NSTask/Helpers/processgroup.m
Various little changes to fix a couple of failing tests under the Windows MSVC toolchain.
=> Windows MSVC test fixes

Source/common.h
Fixes build errors on CI discussed here: https://github.com/gnustep/libs-base/pull/201#issuecomment-901030162
=> Fix building for Windows MSVC with recent toolchain

configure, configure.ac
also add include parameter for checking iconv library, or libc and gnlibiconv might get mixed
=> improve iconv configure for headers

Headers/GNUstepBase/GSBlocks.h, Source/GSSorting.h, Source/NSArray.m, Source/NSData.m, Source/NSDictionary.m, Source/NSFileManager.m, Source/NSOperation.m, Source/NSOrderedSet.m, Source/NSPredicate.m, Source/NSSet.m, Source/NSSortDescriptor.m, Source/NSTimer.m
Calling NSProgress.cancel should not crash when no cancel handler is set.
=> Do not call handler blocks if they are nil

Headers/Foundation/NSObjCRuntime.h
Simple definition of NS_INLINE
=> Definition of NS_INLINE

Headers/Foundation/NSIndexPath.h, Source/NSIndexPath.m
Add needed item, section information in NSIndexPath class
=> Add necessary methods to NSIndexPath to support NSCollectionView

Source/NSTimeZone.m
Fixes the conversion of Windows time zone names to IANA names introduced in #232 on systems not using an English locale, and adds a warning when [`ucal_getTimeZoneIDForWindowsID`](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/ucal_8h.html#ac345a8561828554c092663e541b1c7bd) is unable to map the time zone (in which case it’s documented to return success but a zero length string).
=> Fix time zone lookup on Windows MSVC when using non-English locale

Source/NSURL.m, Tests/base/GSXML/basic.m, Tests/base/NSXMLParser/parse.m
The sloppy parser still has some issues on Windows platforms.
=> NSXML unit test and NSURL file URI fixes

Headers/Foundation/NSStream.h, Source/GSSocketStream.m, Source/unix/NSStream.m, Source/win32/NSStream.m
Added code to support .pac file config in http proxy for windoze.
=> Epf 17843 win32 proxy

ChangeLog, Source/NSPredicate.m, Tests/base/NSPredicate/basic.m
Fixes: https://github.com/gnustep/libs-base/issues/233#issuecomment-1054204110
=> NSPredicate Value Fix

Headers/Foundation/NSFileManager.h, Source/NSFileManager.m
Cherry-picked from the Eggplant/Keysight branch
=> implement setAttributes:ofItemAtPath:error: method

ChangeLog, Source/NSFileManager.m, Tests/base/NSFileManager/general.m
Was returning URLs relative to current working directory instead of given directory.
=> Fix -[NSFileManager contentsOfDirectoryAtURL:...]

Source/Additions/GSXML.m
=> Fix GSXML compatibility with libxml2 v2.11.0

ChangeLog, Headers/Foundation/NSDate.h, Source/NSDate.m
See https://developer.apple.com/documentation/foundation/nsdate/3180113-now?language=objc
=> Implement +[NSDate now]

Headers/Foundation/NSIndexSet.h, Source/NSIndexSet.m, Tests/base/NSIndexSet/enumerateRanges.m
Tested the behaviour of Apple's implementation with the unit tests.
=> NSIndexSet: Implement enumerateRangesUsingBlock: convenience methods

Headers/Foundation/NSExpression.h, MISSING, Source/NSPredicate.m, Tests/base/NSPredicate/basic.m
This PR intends to add the methods...
```
+ expressionWithFormat:argumentArray:
+ expressionWithFormat:
+ expressionWithFormat:arguments:
```
As well as potentially others to the NSExpression class.   I will provide tests for each of these methods.
=> Add 10.6 NSExpression methods

Headers/GNUstepBase/GSConfig.h.in, Source/NSProcessInfo.m, Source/NSUserDefaults.m, Source/win32/GNUmakefile, Source/win32/NSString+Win32Additions.h, Source/win32/NSString+Win32Additions.m
Note that `GetUserPreferredUILanguages` was introduced in Windows Vista.
=> NSUserDefaults: Retrieve native UI languages from Windows and Android System APIs

Tools/AGSHtml.m, Tools/autogsdoc.m
Improvements to AutoGSDoc to enhance CSS styling and HTML5 compatibility
=> Agsdoc new style

Headers/Foundation/NSOrderedSet.h, Headers/Foundation/NSUnit.h
Add documentation to different classes.
=> Add documentation

Headers/Foundation/NSOrderedSet.h
Add documentation for NSOrderedSet.
=> Add documentation for NSOrderedSet
