gnustep/libs-base

- ChangeLog
- Headers/Foundation/NSObjCRuntime.h
Add empty definitions for OSX Availability macros for compatibility
purposes.
> NSObjCRuntime: add availability macro definitions

- Source/NSObject.m
- Tests/base/NSProxy/basic.m
This makes it easier for the runtime to change how reference counts are
stored by removing any refcount manipulation from -base when the runtime
provides accessors.  This should have no functionality change with
existing runtimes, but will let newer runtimes drop in alternative
representations easily.
> Refactor refcount usage.

- ChangeLog
- Headers/GNUstepBase/GSTLS.h
Previously, code checked for whether its defined or not. This
preprocessor  constant might be defined with a zero value
indicating desire not to use GnuTLS, which would still pass the
old check.
Hey, @rfm, can you take a look if this change makes sense? It helps when crosscompiling for a platform that has no GnuTLS, and I /think/ (but didn't check) it won't break our usual platforms.
> GSTLS.h: Change guard to check for /value/ of GS_USE_GNUTLS.

- configure
- configure.ac
Passing --enable-libdispatch was incorrectly disabling libdispatch.
> Fixed libdispatch configuration switch.

- Headers/Foundation/Foundation.h
This more closely aligns Foundation.h with the Apple version if CoreBase and/or libdispatch are available.
The _has_include_ operator is supported by GCC 5 and later and clang, but we check for its availability in order to not break compatibility with other compilers.
> Include CoreFoundation and libdispatch in Foundation.h if available.

- Source/NSLog.m
As there is no way to access stdout/stderr on Android, and syslog is available and outputs to the system log (accesible using "adb logcat"), this improves the developer experience when developing for Android by enabling NSLog output without having to set the "GSLogSyslog" flag.
> Always use syslog for NSLog on Android

- Headers/GNUstepBase/config.h.in
- Source/NSRunLoop.m
- configure
- configure.ac
This updates the libdispatch runloop integration to be compatible with Apple’s [Swift corelibs libdispatch](https://github.com/apple/swift-corelibs-libdispatch) release, which to my knowledge is the most up-to-date and actively maintained release of libdispatch.
In that release, the main queue handle and drain functions have been renamed with a "_4CF" (for CoreFoundation) suffix and have moved to private.h, so we now check for the existance of this header and function names.
Note that libdispatch must be compiled with `INSTALL_PRIVATE_HEADERS=YES`. Please let me know if there is a good place to document this.
Also fixes the checks for the `HAVE_LIBDISPATCH_RUNLOOP` define (was inverted) and ensures that both the handle and drain functions are available (as expected by NSRunLoop.m).
> Add compatibility for Swift corelibs libdispatch release

- ChangeLog
- Headers/Foundation/NSBundle.h
- Source/GSFileHandle.h
- Source/GSFileHandle.m
- Source/NSBundle.m
- Source/NSData.m
- Source/NSFileManager.m
- Source/NSProcessInfo.m
- configure
- configure.ac
This requires passing the Android activity's AssetManager object from Java to GNUstep by calling `+[NSBundle setJavaAssetManager:withJNIEnv:]`, which then enables the following features:
- NSBundle main bundle resource paths support for Android assets, e.g. for `pathForResource:ofType:`, `URLForResource:ofType:` and related methods.
- NSBundle main bundle info dictionary support if Info.plist exists in Android assets.
- `-initWithContentsOfFile:` and related methods support for reading Android assets from main bundle in various classes (e.g. NSData, NSDictionary, NSArray, etc.) by patching NSData `readContentsOfFile()` backbone method.
- NSFileManager `fileExistsAtPath:(isDirectory:)` and `isReadableFileAtPath:` return YES for main bundle asset / asset directory paths.
- NSFileHandle …
> Added support for asset loading on Android.

- Headers/Foundation/NSArray.h
- Headers/Foundation/NSOrderedSet.h
The generic element was not passed on to the superclass.
This meant that any method from the superclass would not have the generics information. For example, calling `objectAtIndex:` (defined in NSArray) on an NSMutableArray instance would not return the generic type.
This also removes the `__covariant` annotation on NSMutableOrderedSet, which I think is only needed on the superclass NSOrderedSet (same for NSArray, matches the Apple headers).
> Fix generics definition of NSMutableArray and NSMutableOrderedSet

- .travis.yml
The CI tests on travis were failing after each commit because libblocksruntime-dev was not included.  This pull requests simply adds libblockruntime-dev to the installed dependencies.
> Added libblocksruntime-dev to fix failing tests

- ChangeLog
- Headers/Foundation/NSArray.h
- Headers/Foundation/NSOrderedSet.h
These methods set/return properties of the elements, not the elements themselves.
Also updated change log with this and my previous change.
> Fix NSArray and NSOrderedSet KVC method types to not use generic type.

- Source/NSOperation.m
NSOperation was removing self as an observer of "isFinished" both in the KVO callback and in dealloc.
While this is a no-op with the current implementation of `-removeObserver:forKeyPath:`, it would cause an error if/when the implementation is changed to throw an error when unregistering non-registered observers (as is the case on Apple platforms).
> Fixed NSOperation calling removeObserver more than once.

- Source/Additions/Unicode.m
Android uses UTF-8 as default encoding, e.g. for file paths.
This fixes file handling support for paths containing non-ASCII characters on Android, which would previously throw an exception as they couldn't be converted to C strings using ISO Latin 1 encoding.
(Please let me know if there’s a better place than in GSPrivateCStringEncoding() to make this change.)
> Use UTF-8 as default encoding on Android.

- Source/Additions/NSObject+GNUstepBase.m
- Source/NSDebug.m
- Source/NSObject.m
In [dd368559] Richard forgot to include the <malloc.h> guards. I saw that in the past Riccardo added special guards for OpenBSD, but IMO this shouldn't be necessary.
> Guard inclusion of <malloc.h> as to not break FreeBSD

- Headers/Foundation/Foundation.h
- Headers/Foundation/MISSING
- Headers/Foundation/NSFileWrapper.h
- Source/GNUmakefile
- Source/NSFileWrapper.m
- Version
NSFileWrapper was migrated to Foundation from AppKit in macOS 10.7. This change implements that move for GNUstep.
> Move NSFileWrapper to Foundation

- ChangeLog
- Headers/Foundation/NSProcessInfo.h
- Source/NSPathUtilities.m
- Source/NSProcessInfo.m
This makes GNUstep use the path returned by `Context.getFilesDir()` as the basis for storing data (e.g. NSUserDefaults) and when querying system directory paths (NSLibraryDirectory, NSApplicationSupportDirectory, etc.).
Requires calling a new `GSInitializeProcessAndroid()` initialization function on Android to enable this support.
> Added support for data directory on Android.

- Source/NSDictionary.m
- Tests/base/NSDictionary/sort.m
NSDictionary keysSortedByValueUsingComparator: appears to have a bug.  It does not actually return the keys sorted by the values.  (Instead it appears to be sorting the keys based on their own value rather than the value each maps to in the dictionary...)
> Fixing NSDictionary keysSortedByValueUsingComparator:

- ChangeLog
- Source/NSDictionary.m
Assigning nil value via keyed subscript now correctly removes object for key.
This matches the documented reference implementation:
https://developer.apple.com/documentation/foundation/nsmutabledictionary/1574187-setobject?language=objc
> Fixed mutable dictionary keyed subscript behavior.

- Headers/Foundation/NSDate.h
- Source/NSDate.m
Matches Apple platform implementations and enables using property syntax like `NSDate.date.timeIntervalSince1970`.
> Updated NSDate to use instancetype.

- ChangeLog
- Headers/Foundation/NSHashTable.h
- Headers/Foundation/NSMapTable.h
Adds generics support to NSMapTable and updates NSMapTable and NSHashTable to use "instancetype".
(We previously added generics support to NSHashTable in #57.)
> Added generics support to NSMapTable

- Source/GNUmakefile
This header is included in Foundation.h but was not exported.
> Added FoundationLegacySwiftCompatibility.h to Foundation headers

- ChangeLog
- Headers/GNUstepBase/config.h.in
- Source/NSException.m
- configure
- configure.ac
Adds NSException backtrace support using libunwind for platforms where the other facilities like `backtrace()` are not available (e.g. Android).
While unfortunately the backtrace will not include Objective-C symbols (because `dladdr()` does not support these), it fixes the app crashing in `NSCountFrames()` on Android when an exception is thrown. If anyone has a pointer how to obtain Objective-C symbols please let me know.
Also contains a [small improvement](https://github.com/gnustep/libs-base/pull/83/files#diff-42146764331f4ac76b55f9724cc604f4R1302-R1303) in the symbol frame formatting for platforms without any of the supported backtrace libraries (previously the frame pointer would be printed as `{pointer=0x1234;}` instead of just `0x1234`).
> Added NSException support for libunwind

- travis-deps.sh
Adding setup for libobjc2 submodules, if builds correctly can be merged into #84
> Set up libobjc2's git submodules for travis CI

- ChangeLog
- Headers/Foundation/NSProcessInfo.h
- Source/NSPathUtilities.m
- Source/NSProcessInfo.m
Added support for NSTemporaryDirectory() on Android using subfolder in folder returned by [Context.getCacheDir()](https://developer.android.com/reference/android/content/Context#getCacheDir()), as there is no official temp dir prior to API level 26. Clean up temp dir on launch in GSInitializeProcessAndroid().
Also use Context.getCacheDir() as NSCachesDirectory (with NSUserDomainMask) on Android.
Also removes some dead code in NSTemporaryDirectory() and avoids fetching file attributes of temp dir on platforms where attributes are unused (i.e. Win32, Cygwin, Android).
> Added support for temp and caches dir on Android.

- .travis.yml
- travis-deps.sh
This updates the Travis CI with the following fixes and changes for builds using Clang and the `ng-gnu-gnu` library combo:
- Fixed `--disable-mixedabi` option spelling. The previous spelling was incorrect and ignored, as indicated by the following warning in the current travis builds:
`WARNING: unrecognized options: --disable-mixed-abi`
- Updated GNUstep make repository URL. The old URL was being redirected to the new URL by GitHub, so this does not change the repository.
- Removed obsolete --enable-objc-nonfragile-abi flag (was removed in https://github.com/gnustep/libs-base/commit/38fc2bde8226e7a88a9a3f21b104d2b2eb6c4bed).
- Adds builds using the gnustep-2.0 runtime (with and without mixed ABI).
- Adds output from `gnustep-config --objc-flags` so it’s possible to verify that the …
> Travis fixes and gnustep-2.0 runtime support

- .travis.yml
- Tests/base/NSArray/blocks.m
Travis isn't currently *really* running Ci for base built with the 2.0 runtime ABI. This PR fixes that. The magic sauce here is to use at least clang 8 and some linker which is not ld.bfd.
I've also fixed one of the blocks related NSArray tests which wasn't accounting for concurrency properly.
> Fix CI for runtime ABI 2.0

- .travis.yml
- ChangeLog
- Source/NSRunLoop.m
- Tests/base/NSRunLoop/dispatch.m
- travis-deps.sh
It seems like the runloop integration for the libdispatch main queue broke down a bit – unfortunately in a quite symmetrical way so that both the implementation and the tests would never be built, even if a compatible version of libdispatch existed (it was checking for `HAVE_LIBDISPATCH_RUNLOOP` where it should have been using `GS_USE_LIBDISPATCH_RUNLOOP`).
That uncovered a few problems with libdispatch from swift-corelibs. Our side of that is fixed here (simple typos, mostly), the libdispatch side of things is addressed in apple/swift-corelibs-libdispatch#534.
I've also freshened up the Travis CI job a bit in the process so that this is continuously tested again.
> Fix runloop integration for libdispatch from swift

- Headers/GNUstepBase/GSIMap.h
- Source/NSConcreteHashTable.m
- Source/NSConcreteMapTable.m
The existing code was assuming that weak object pointers were safe to
read directly, without going via the read barrier, which is incorrect.
It was also attempting to retain the result in some places.  The new
code is hopefully somewhat more correct.
> Rework some of the weak handling for NS{Map,Hash}Table.

- ChangeLog
- Tests/base/NSHashTable/weakObjects.m
- Tests/base/NSMapTable/weakObjects.m
I wrote these tests in order to track down the issues we’re seeing with weak pointer support in NSHashTable and NSMapTable that I outlined on the mailing list:
https://lists.gnu.org/archive/html/discuss-gnustep/2019-10/msg00008.html
The tests pass when run against Apple’s Foundation, but are failing for me when run on Android. I’d like to understand whether other configurations are affected as well (e.g. the CI test builds).
If they are failing on the CI I’d appreciate any fixes or insights into why that is the case. If they pass, please feel free to merge – we will then know to look for the issue in our toolchain configuration.
> Added tests for NSHashTable/NSMapTable weak objects support

- Source/Additions/NSObject+GNUstepBase.m
Silences warnings "function declared 'noreturn' should not return [-Winvalid-noreturn]".
> Fixed incorrect while loops for noreturn functions

- Headers/Foundation/NSUUID.h
- Source/NSUUID.m
Matches Apple’s implementation and enables using the dot syntax with NSUUID e.g. like this: `NSUUID.UUID.UUIDString`.
> Updated NSUUID to use instancetype.

- Source/NSTimer.m
Fixes the bugs with the implementation of NSTimer for blocks:
- moves the ASSIGN statement for the block to before the return statement.  (It was after the return statement, and so was never getting executed)
- prevents the block from being set to nil.  (Not sure why it was being set to nil.)
> Fix timer blocks bug

- .gitignore
libs-base contains base.xcodeproj so this makes sense
> gitignore update according to https://www.gitignore.io/api/xcode

- configure.ac
Debian has begun removing `xml2-config` from its libxml2-dev package, meaning `configure` fails to find libxml2.
This patch modifies `configure.ac` to use `PKG_CHECK_MODULES` to detect libxml2.
> configure.ac: Use PKG_CHECK_MODULES to detect libxml2

- Headers/Foundation/NSPropertyList.h
Base64 parsing is supported since 3f2fa9ddfe507b68fd92843c345c7994b1c1adc8 and it is the default since 9aa5d4cd0403c2d990262c15884181da5d1e32ae. We should definitely document that.
> NSPropertyList.h: mention base64 encoding

- .travis.yml
- travis-deps.sh
The CI jobs for the older GNUstep Objective-C ABI were failing because newer gnustep-make versions were implicitly upgrading the build to the gnustep-2.0 ABI. This PR fixes that by stating explicitly which runtime ABI should be used.
> fix CI build for gnustep ABI < 2.0

- Headers/Foundation/NSURL.h
Enables using the dot syntax with NSURL e.g. `[NSURL URLWithString:@"/"].standardizedURL`.
> Updated NSURL to use instancetype.

- ChangeLog
- Tests/base/NSBundle/GNUmakefile.preamble
- Tests/base/NSBundle/Resources/GNUmakefile
- Tests/base/NSBundle/TestInfo
- Tests/base/NSBundle/resources2.m
I was trying to write a test that would allow to automatically test the clang libobjc2 issue we are currently fixing on make. As I do not use this environment myself this is just a blind guess. 
For this I reused a test by Niels and rewrote that to load the framework differently, hoping that this will trigger the issue.
> Extend NSBundle test to check for framework resource loading.

- ChangeLog
- Source/NSURL.m
This happened when setting an URL that didn't have all the different parts like fragment or query, as rangeOfString: throws for nil values.
Also correctly initializes rangeOf* properties with `{NSNotFound, 0}`.
> Fixed NSURLComponents setURL: throwing exceptions.

- ChangeLog
- Headers/Foundation/NSError.h
- Source/NSError.m
This was [added](https://developer.apple.com/documentation/foundation/nserrordomain?language=objc) in the macOS 10.12 SDK.
> Added NSErrorDomain typedef.

- ChangeLog
- Source/NSString.m
more consistent and correct for ICU 65.
The old code resulted in numerical comparisons failing with ICU65, because the code was just ignoring the system locale. I moved the tow different preprocessing instructions into the  function GSICUCollatorOpen and removed the obviously wrong code path.
The code is at least better than the previous version, I am not sure whether it is already correct for all cases.
> * Source/NSString.m: Attempt to make calls to GSICUCollatorOpen()

- ChangeLog
- Source/NSURLResponse.m
When creating an instance of  NSHTTPURLResponse using:
`[NSHTTPURLResponse initWithURL:statusCode:HTTPVersion:headerFields:]`, the `MIMEType` property currently returns the content-type header value including any attributes in the header fields (e.g. `application/json;charset=utf-8`), whereas it should just return `application/json`.
This patch forces the content-type header parsing down the correct route in GSMime.m so that `MIMEType` returns the correct value.
> Fixed parsing of NSURLResponse content type header.

- ChangeLog
- Source/NSThread.m
Fixes setting thread name on Android where errno is not set when the string is too long (`ERANGE`):
https://android.googlesource.com/platform/bionic/+/master/libc/bionic/pthread_setname_np.cpp#90
I think this change might also be needed for other platforms. E.g. glibc also doesn’t seem to set errno in this case:
https://github.com/bminor/glibc/blob/d614a75/sysdeps/unix/sysv/linux/pthread_setname.c#L39-L40
According to the [man page](http://man7.org/linux/man-pages/man3/pthread_setname_np.3.html), `pthread_setname_np` directly returns an error, so I think this should be portable:
> **Return value**
> On success, these functions return 0; on error, they return a nonzero error number.
> Use pthread_setname_np result instead of errno.

- ChangeLog
- Source/NSOperation.m
The NSOperation completion block was not being copied/retained or released.
I’m not totally sure if it’s better to use the Block_copy()/Block_release() functions here, or if I should/can use e.g. the ASSIGNCOPY()/RELEASE() macros instead. GSNotificationObserver uses to former, which is why I went with them.
> Fixed NSOperation completion block memory management.

- Tests/base/NSString/test09.m
Added new tests for -[NSString stringByRemovingPercentEncoding], updated existing test for percent string encoding with PASS_EQUAL, as were suggested by fredkiefer and rfm. 
Checked tests with Apple's Foundation. Two tests have failed on the current master:
Failed test:     test09.m:57 ... Percent-encoding two-byte character
Failed test:     test09.m:67 ... Percent-encoding all characters in the string
Looks like -stringByAddingPercentEncodingWithAllowedCharacters: unable to encode a string ending with two-byte characters
> NSStrings percent decoding test

- Source/NSJSONSerialization.m
In NSJSONSerialization
When the buffer size exceeds 128, `parseNumber()` does not parse correctly.
When parse 12800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, **It's result in 0**.
The first time `bufferSize` is extended, `number` loses the previously parsed characters in `numberBuffer` .
The probrem is here.
```c
if (number == numberBuffer)\
number = malloc(bufferSize);\
else\
number = realloc(number, bufferSize);\
```
Until the bufferSize reaches 128, number is the pointer to numberBuffer, and the parsed characters are stored in numberBuffer.
But here, `number` has lost characters in `numberBuffer` .
Return value of parseNumber() is generated from a `number` .
So, when the buffer size exceeds 128, `number` …
> Fix loss of buffer in NSJSONSerialization.

- ChangeLog
- Headers/Foundation/NSXMLParser.h
- Headers/GNUstepBase/GSXML.h
- MISSING
- Source/Additions/GSXML.m
- Source/NSXMLParser.m
- Tests/base/NSXMLParser/parse.m
This uses an I/O parser (streaming the data into the parser) instead of a push parser, which should result in reduced memory requirements when parsing large XML files over `-initWithData:`.
Also [changes](https://github.com/gnustep/libs-base/pull/130/files#diff-049b8082c6e5b42981048909755c7aaeL483-R487) `-[NSXMLParser initWithContentsOfURL:]` to use `-[GSXMLParser initWithSAXHandler:withContentsOfURL:]` for consistency, which internally does the same thing as before, i.e. read the URL into an NSData.
> Implement -[NSXMLParser initWithStream:].

- ChangeLog
- Headers/Foundation/NSLocale.h
- Source/NSLocale.m
- Use "instancetype" for instance-returning methods.
- Fix method signature of -displayNameForKey:value: to match Apple, and since implementation expects NSString.
> NSLocale improvements

- Source/NSJSONSerialization.m
In NSJSONSerialization
When the number has invalid exponent, parseNumber() does not stop parse.
The problem is here.
```
// parse the exponent if there is one
if ('e' == tolower(c))
{
BUFFER(c);
c = consumeChar(state);
// The exponent must be a valid number
if (!(c == '-' || c == '+' || isdigit(c)))
{
if (number != numberBuffer)
{
free(number);
number = numberBuffer;
}
}
BUFFER(c);
while (isdigit(c = consumeChar(state)))
{
BUFFER(c);
}
}
```
The comment `// The exponent must be a valid number` is right.
I think validation ( `if (!(c == '-' || c == '+' || isdigit(c)))` ) is also correct.
But in the if statement for an invalid number, it doesn't call parseError(), and it doesn't interrupt parse.
As a result, it continues `BUFFER(c);` even if it is an invalid number.
In the if statement for …
> Fix exponent validation in NSJSONSerialization

- ChangeLog
- Source/win32/GSFileHandle.m
- Source/win32/NSMessagePort.m
Low-hanging fix to ensure `GS_EXPOSE()` doesn’t hide the instance variables when building Windows sources. Copied `EXPOSE_XXX_IVARS` defines from corresponding Unix-classes.
> Fix building Win32 classes with nonfragile ABI.

- ChangeLog
- Source/NSUserDefaults.m
- Tests/base/NSUserDefaults/general.m
Changes `-[NSUserDefaults setBool:forKey:]` to store a bool NSNumber instead of a YES/NO string.
I am not sure why a string was used here, but this seems more correct, and it should make no difference when reading the value via `-[NSUserDefaults boolForKey:]` or `[[NSUserDefaults objectForKey:X] boolValue]`.
We had a code path that was observing NSUserDefaults and was expecting the new value to be an NSNumber (which is the case on Apple platforms).
> Store NSNumber instead of NSString for NSUserDefaults -setBool:forKey:.

- .travis.yml
- ChangeLog
- Headers/Foundation/NSException.h
- Headers/GNUstepBase/GSConfig.h.in
- Source/GSNetwork.h
- Source/win32/GSFileHandle.m
- config/config.reuseaddr.c
- travis-deps.sh
This adds Windows as a CI target using MinGW-w64 by following these instructions:
https://docs.travis-ci.com/user/reference/windows/#how-do-i-use-msys2
The required packages are taken from the [MSYS2 instructions](http://wiki.gnustep.org/index.php/Installation_MSYS2), with the addition of packages for ICU.
The current status is:
* 64-bit target:
* builds [successfully](https://travis-ci.org/github/gnustep/libs-base/jobs/687727959#L6167) (albeit with many more warnings than on Unices)
* running the tests [fails](https://travis-ci.org/github/gnustep/libs-base/jobs/687727959#L6403), but I’m not sure why
* 32-bit target [fails building](https://travis-ci.org/github/gnustep/libs-base/jobs/687727958#L1196)
I’m not sure about the amount of work required to get tests working and 32-bit builds to …
> Set up CI for Windows using MinGW and GCC

- ChangeLog
- Source/NSConcreteMapTable.m
- Tests/base/NSMapTable/weakObjects.m
Replacing an existing value in a hash table was setting the pointer before calling `pointerFunctionsAssign()`. In the case of weak objects, this meant that the pointer was already the new value before `objc_storeWeak()` was called, causing the weak pointer to not be updated correctly.
> Fix replacing existing value in a weak objects map table

- Headers/Foundation/NSFilePresenter.h
Also removed `@required` as I think protocol methods are required by default.
> Fix optional NSFilePresenter methods not being declared as optional.

- ChangeLog
- Source/NSBundle.m
- Source/NSFileManager.m
Fixes:
* `-[NSBundle pathForResource:ofType:]` not finding directories in Android assets.
* `-[NSFileManager isReadableFileAtPath:]` always returning NO for directories in Android assets.
> Android assets improvements to support directories

- configure
- configure.ac
Adds defining `HAVE_ICONV` to the configure cross-compilation branches.
> Fix finding libiconv via cross.config

- ChangeLog
- Source/NSValueTransformer.m
- Tests/base/NSValueTransformer/basic.m
Use NSRecursiveLock in NSValueTransformer to allow recursive creation of transformers. This matches macOS behavior (i.e. no deadlock when recursively creating transformers).
> Fix deadlock on recursive creation of NSValueTransformer

- ChangeLog
- Source/NSThread.m
Fixes a possible recursion and deadlock from `gnustep_base_thread_callback()` when setting up the autorelease pool inside the thread lock, as `-[NSAutoreleasePool allocWithZone:]` calls `GSCurrentThread()`, which may end up calling `GSRegisterCurrentThread()` and thereby `gnustep_base_thread_callback()` in some circumstances.
> Fix possible deadlock when becoming multi-threaded.

- Headers/GNUstepBase/config.h.in
- Source/GSSocketStream.m
- Source/NSHost.m
- Source/inet_ntop.m
- Source/inet_pton.m
- Tools/gdomap.c
- configure
- configure.ac
after some discussion with Fred and Frederick and several local test, I come up with this.
Although it is a mystery (the whole cause is that in 32bit MSYS2, inet_ntop is not found in the same library where it is found in 64bit version, so we need a replacement.
Thus I created a replacement which does not clash and works better. If we can in future make the configure check better, then fine.
This pull-request should make #34 obsolete too and concentrate on why URL stuff times out (now coherently in 32bit and 64bit MSYS2).
> Fix MSYS2-32

- ChangeLog
- Source/NSLog.m
- Source/NSProcessInfo.m
Always set GSLogSyslog flag on Android instead of using #ifdefs. This enables other checks for this flag (e.g. not logging date/time to syslog) that were previously inactive on Android.
This is an improvement over #43.
> Improve NSLog output on Android.

- ChangeLog
- Source/NSLog.m
This makes the log more succinct when GSLogThread is enabled and the system doesn't provide an OS-level thread ID (i.e. GSPrivateThreadID() returns GSCurrentThread()), which would previously cause the NSThread pointer to be logged twice.
> Don't log current thread if its identical to private thread ID.

- Source/GSICUString.h
ICU 68 no longer defines the `TRUE` and `FALSE` defines, as outlined in their updated [Coding Guidelines](https://github.com/unicode-org/icu/blob/master/docs/userguide/dev/codingguidelines.md#primitive-types). This causes building GNUstep with ICU 68 to fail.
> Fix compilation with ICU 68

- .travis.yml
This should help with tracking down compilation issues like the ones we are seeing on Windows 32-bit:
https://travis-ci.org/github/gnustep/libs-base/jobs/697202242#L23769
> Output config.log if build fails on CI.

- configure
- configure.ac
This PR makes two changes to fix and improve building on Windows with MinGW-w64 and libobjc2. Posting this as a draft since my Autoconf knowledge is very limited and there are probably issues with my changes or better ways to do this. Feedback welcome.
1. Detect objc.dll and temporarily copy it to source directory.
This fixes the following error during configure, which happens because conftest.exe can’t find objc.dll at runtime. By default Windows executables search for dlls in the working directory, so we simply copy and remove it at the end (but only if configure succeeds – is there a way to have a hook that gets executed at the end?).
```
checking whether objc really works... no
I don't seem to be able to use your Objective-C compiler to produce
working binaries!  Please check your …
```
> Windows fixes

- configure
- configure.ac
This moves the check for `curl/curl.h` further up so that `HAVE_LIBCURL` is only enabled if both the library and the headers were found.
Fixes cross-compiling in an environment where the host has curl-config, but the target doesn’t have libcurl, e.g. when building for Android on a macOS host.
I’m no expert at Autoconf, so please let me know if there there’s better way to do this and I’m happy do change the patch.
> Disable libcurl support when headers are not found

- ChangeLog
- Tools/GNUmakefile
gdomap doesn’t compile when building for Android.
This patch was previously done manually in tools-android.
> Disable gdomap on Android

- Tools/GNUmakefile
#169 was not working for all ABIs, as target OS can be either "linux-android" or "linux-androideabi" (when building for armeabi-v7a).
> Disable gdomap for all Android ABIs.

- ChangeLog
- Headers/Foundation/NSTimer.h
- Source/NSTimer.m
We already had `-scheduledTimerWithTimeInterval:repeats:block:`, this is just adding the unscheduled variant `-timerWithTimeInterval:repeats:block:`.
> Add unscheduled NSTimer block initializer.

- Documentation/HtmlNav/index.html
I only left the broken link to **Developer/CodingStandards/coding-standards_toc.html** because I may be overlooked what component creates the content of that link.
> * fixed broken links in Documentation/HtmlNav/index.html

- Headers/Foundation/NSDecimalNumber.h
- Headers/Foundation/NSException.h
- Headers/Foundation/NSFormatter.h
- Headers/Foundation/NSHTTPCookie.h
- Headers/Foundation/NSHTTPCookieStorage.h
- Headers/Foundation/NSIndexPath.h
- Headers/Foundation/NSIndexSet.h
- Headers/Foundation/NSInvocationOperation.h
- Headers/Foundation/NSSet.h
- Headers/Foundation/NSURLCredentialStorage.h
- Headers/Foundation/NSURLError.h
- Headers/Foundation/NSURLProtectionSpace.h
- Headers/GNUstepBase/GSTLS.h
- Source/GSFastEnumeration.h
- Source/GSFileHandle.m
- Source/NSInvocationOperation.m
- Tests/base/NSFileHandle/singleton.m
Somehow I had missed a couple more... I hope this should be it tho.
Note that we’re currently not exporting the GS* classes, not sure if we should?
I did add `GS_EXPORT` to the `GSTLS*` string constants, as they are also already defined like this in NSFileHandle.h and the definitions should match.
> Add missing GS_EXPORT(_CLASS) annotations

- ChangeLog
- Headers/GNUstepBase/GSVersionMacros.h
- Source/NSObject.m
Windows doesn’t support resolving weak symbols, so we need to guard the retain/release libobjc2 support on `__GNUSTEP_RUNTIME__` instead of `SUPPORT_WEAK`. And we also need a `__declspec(dllimport)` annotation on the libobjc2 functions so they are resolved from the DLL.
The new `GS_IMPORT` macro should be added in other places too where we declare externally defined functions.
> Add support for libobjc2 runtime in NSObject on Windows

- ChangeLog
- Source/Additions/Unicode.m
Using Clang MSVC on 64-bit Windows was interpreting the constants in the `NSStringEncoding` enum as `int` (which is [according to the C standard](https://stackoverflow.com/q/366017/1534401)), which meant that the `NSUTF16*EndianStringEncoding` and `NSUTF32*StringEncoding` were interpreted as negative numbers due to their topmost bit being set, which caused the `EntryForEncoding()` function to always fail for these constants.
I’m not sure in how far this affects other compilers/platforms, although it seems like it might affect all.
> Fix lookup of string encodings with high numeric values in encoding table

- Headers/GNUstepBase/NSDebug+GNUstepBase.h
The motivation is that these are more like keys to specific logging domain names, not log levels. If you think of log levels, you usually think of the syslog style debug/info/warn/error levels where enabling logs at any one level implies enabling those at all levels above. Our log keys aren't ordered in that way. The texinfo docs were inconsistent in using "level" and "key" as the argument and we already changed that to use "key" throughout" this change makes the header and auto docs consistent.
> Reword NSDebug*LLog "level" argument to "key"

- Documentation/manual/ExceptionHandling.texi
The argument was named "level" in the docs but it's preferable if it's called "key" because then you can see the parallels with `NSDebugLLog`.
> Rename first argument to NSDebug[MF]LLog to make it easier to understand

- ChangeLog
- Source/Additions/Unicode.m
Possible heap corruption in `GSFromUnicode()` because `sprintf()` always appends NULL terminator, which is written past the end of the `ptr` buffer for the last character in the string.
Was exposed by existing `NSString/basic` test when checking for "latin1 in lossy encoding", as the last character of that string is running into the affected code. When running tests using the Windows MSVC toolchain this was showing a "HEAP CORRUPTION DETECTED" error.
> Fix possible heap corruption when converting to NSNonLossyASCIIStringEncoding

- ChangeLog
- Source/GSICUString.h
- Source/GSICUString.m
The `TEMP_BUFFER()` macro was making some incorrect calculations. This is used extensively in `NSRegularExpression` and also in `GSUTextMutableString` (which however doesn’t seem to be used).
With `sizeof(unichar) == 2`, the `onstack` variable was initialized for 32 bytes (= 16 characters), while the `onheap` variable (used with more than 64 characters) was only half the size needed.
Note that the macro is always called with the string length and not the buffer size, so I renamed the variable from `size` to `length`.
Note that this increases the `onstack` variable to be 64 bytes, as noted in the macro’s comment. We could also keep this 32 bytes if preferred.
> Fix possible memory corruption in string handling

- ChangeLog
- Headers/Foundation/NSLock.h
- Headers/Foundation/NSThread.h
- Headers/GNUstepBase/GSConfig.h.in
- Headers/GNUstepBase/config.h.in
- Source/Additions/GCObject.m
- Source/Additions/GSObjCRuntime.m
- Source/Additions/Unicode.m
- Source/GSAtomic.h
- Source/GSFFCallInvocation.m
- Source/GSFFIInvocation.m
- Source/GSPThread.h
- Source/NSArray.m
- Source/NSCharacterSet.m
- Source/NSDebug.m
- Source/NSException.m
- Source/NSLock.m
- Source/NSObject.m
- Source/NSScanner.m
- Source/NSString.m
- Source/NSThread.m
- Source/NSTimeZone.m
- Source/NSZone.m
- Tests/base/NSThread/GNUmakefile.preamble
- Tests/base/NSThread/late_unregister.m
- Tests/base/NSThread/lazy_thread.m
- config/config.initialize.m
- configure
- configure.ac
This PR adds support for native locks on Windows, as previously suggested by David on the mailing list. I subsequently plan to also add native threading support in NSThread and thereby remove the dependency on the pthread library on Windows.
While the second part is still outstanding, I wanted to get feedback on the changes early on to ensure this is going in the right direction, and I’d appreciate your initial feedback @rfm and @davidchisnall.
The support for native locks uses the following Windows APIs:
- [Slim Reader/Writer (SRW) locks](https://docs.microsoft.com/en-us/windows/win32/sync/slim-reader-writer--srw--locks) in exclusive mode for any non-recursive locks, which should be the fastest kind of locks available on Windows from what I’ve read
- [Critical Section …
> Add support for native locks and threading on Windows

- ChangeLog
- Headers/GNUstepBase/config.h.in
- Source/Additions/Unicode.m
- Source/GSICUString.h
- Source/NSCalendar.m
- Source/NSDateFormatter.m
- Source/NSLocale.m
- Source/NSNumberFormatter.m
- Source/NSPredicate.m
- Source/NSRegularExpression.m
- Source/NSString.m
- Source/NSTimeZone.m
- configure
- configure.ac
As suggested by @davidchisnall in https://github.com/gnustep/tools-windows-msvc/issues/2, this PR adds support for using the [Windows-provided ICU libraries](https://docs.microsoft.com/en-us/windows/win32/intl/international-components-for-unicode--icu-) when using the MSVC toolchain (I don’t think they can be used under MinGW). Using this requires Windows 10 version 1903 (May 2019 Update) or later.
The main change is in configure, where we now check for `icu.h` and `icu.dll` as a backup if the main check for ICU headers fails, plus using the merged `icu.h` that Windows provides instead of the individual `unicode/*.h` headers.
Also adds missing configure check for unicode/utext.h.
> Add support for using ICU DLL from Windows 10 when using MSVC toolchain

- ChangeLog
- Headers/GNUstepBase/config.h.in
- configure
- configure.ac
Use pkgconfig instead of manual checks to find libxslt. Fixes finding library in cross-compilation environments and when library has further dependencies (e.g. when using MSVC toolchain).
> Use pkgconfig to find libxslt

- Headers/Foundation/NSURL.h
- Headers/GNUstepBase/GSIMap.h
- Source/NSURL.m
I noticed that the **initFileURLWithPath:relativeToURL:**, **initFileURLWithPath:isDirectory:relativeToURL:**, **fileURLWithPath:relativeToURL:** and **fileURLWithPath:isDirectory:relativeToURL:** initializers (and convenience initializers) are not present in gnustep-base. They were added in macOS 10.11.
Here is a full implementation of all initializers listed above with some cleanup in the initialization process (duplicate code removal).
My editor automatically formats the source as described in the _.clang-format_ file. Turns out that the source code did not follow the spec. Most of the changes are automatic clang-format adjustments.
> New NSURL initializers (macOS 10.11 initFileURLWithPath:relativeToURL:) and cleanup

- Source/Additions/GSObjCRuntime.m
- Source/GSConcreteValueTemplate.m
- Source/GSValue.m
- Source/NSKeyedUnarchiver.m
- Source/NSURL.m
- Source/NSValue.m
- Tests/base/NSValue/basic.m
The argument order is `(*sizep, *alignp)`, but it was often incorrectly used the other way around.
This is probably the source of several bugs, but the one that hit me was that an `NSValue` containing `NSRange` didn't return the proper value in `-getValue`. I've added a test for that case, correct me if it's wrong, I'm not familiar with your testing setup.
> Fix `NSGetSizeAndAlignment` usage

- Source/NSKeyedUnarchiver.m
- Source/NSNotificationCenter.m
On Apple platforms, `nil` is defined as `NULL`, whereas libobjc2 defines it as `(id)((void*)0)`.
I’ve created https://github.com/gnustep/libobjc2/pull/212 to have libobjc2 match Apple’s implementation, but this results in errors when building libs-base because the GSUNION for GSIArrayItem doesn’t contain an entry for `void*`. This change adds the required cast in libs-base, which doesn’t hurt if it’s already present in the runtime.
> Add required cast in case nil is not defined as id

- ChangeLog
- Headers/Foundation/NSBundle.h
- Headers/GNUstepBase/GSVersionMacros.h
Fixes warnings like the following when using a localized string as a format argument:
```c
[NSString stringWithFormat:NSLocalizedString(@"localized string")]
warning: format string is not a string literal (potentially insecure) [-Wformat-security]
```
> Annotate NSBundle localized string function with NS_FORMAT_ARGUMENT

- Headers/GNUstepBase/GSVersionMacros.h
The macro causes the following warning even with recent GCC versions:
`'format_arg' attribute directive ignored [-Wattributes]`
This disables the macro with GCC as discussed on the mailing list.
> Restrict NS_FORMAT_ARGUMENT() to Clang.

- ChangeLog
- Source/Additions/Unicode.m
- Source/NSBundle.m
- Source/NSString.m
Background: We usually use Xcode to edit our Localizable.strings files for all platforms, which defaults to writing them in UTF-8. Currently when launching our app we get a warning about "Localisation file ... not in portable encoding" for every strings file being loaded. Unfortunately we cannot fix this by adding a BOM marker, as Xcode will reliably delete it on every change.
I’m not sure what "the original standard" in the comment in NSBundle.m refers to exactly, but it seems to me that defaulting to ASCII might no longer be the best choice (the [original commit](https://github.com/gnustep/libs-base/commit/9526fb065f59463b2856c03dbe612fffb2990ad7) that introduced this logic is 13 years old). With this change we now always use `[NSString defaultCStringEncoding]` when reading strings …
> Default to UTF-8 when reading localized string files

- ChangeLog
- Source/NSOperation.m
- Tests/base/NSOperation/concurrent.m
- Concurrent operations never called the completion block.
- In the "isFinished", the observer code in both NSOperation and NSOperationQueue assumed that isFinished was YES when the KVO notification was triggered, but this doesn’t have to be the case.
- The "isFinished" observer for a dependency was removed both when the notification triggered and when the dependency was removed. This assumes an implementation detail of our current KVO implementation, which doesn’t throw an exception if an observer is not actually registered (Apple platforms do). (We previously fixed the same issue for the operation itself in https://github.com/gnustep/libs-base/commit/ae10f58dc456a954d06ecc57376c8e77e9b243ae).
I also added tests for the first two issues (which …
> Fix handling of concurrent NSOperations

- ChangeLog
- Source/NSData.m
- Source/NSFileManager.m
- Source/NSPathUtilities.m
- Source/NSTimeZone.m
- Source/win32/GSFileHandle.m
This comprise a couple of improvements mainly targeting Windows:
- Fix NSTimeZone lookup on Windows MSVC, by converting the Windows time zone names to IANA names used in the NSTimeZone resources ([more info](https://devblogs.microsoft.com/oldnewthing/20210527-00/?p=105255)).
- Fix `NSTemporaryDirectory()` returning a path with backslashes on Windows, even though we use forward slashes for all internal path handling (with -fileSystemRepresentation converting forward to backward slashes to pass paths to system APIs).
- Non-functional: use `GSNativeChar` in various places handling paths instead of #ifdefs and `unichar` (which is defined as `uint16_t` like `GSNativeChar`).
> Various improvements (mainly) for Windows

- Source/NSURL.m
The method description of **-[NSURL loadResourceDataNotifyingClient: (id)client   usingCache:(BOOL)shouldUseCache  ]** states:
_If **shouldUseCache** is YES then an attempt will be made to locate a cached NSURLHandle to provide the resource data, otherwise a new handle will be created and cached._
The current implementation doesn't follow that and always use the handle from the cache regardless of the **shouldUseCache**.
It is the source of the following bug in Grr [https://savannah.nongnu.org/bugs/index.php?56712](url). 
If the user subscribed to several feeds from the same site (e.g. yotube channels) the action "Fetch all" calls the -**[NSURL loadResourceDataNotifyingClient: usingCache: NO ]** consequently.  The libs-base disregards the **usingCache** and uses the same cached handle for …
> use handle from the cache only if the caller asked

- ChangeLog
- Headers/Foundation/NSCalendar.h
- Source/NSCalendar.m
- Tests/base/NSCalendar/basic.m
- Tests/base/NSCalendar/component-diff.m
- Tests/base/NSCalendar/era.m
This PR adds 10.9 methods for:
```
#if OS_API_VERSION(MAC_OS_X_VERSION_10_9, GS_API_LATEST)
- (void) getEra: (NSInteger *)eraValuePointer
year: (NSInteger *)yearValuePointer
month: (NSInteger *)monthValuePointer
day: (NSInteger *)dayValuePointer
fromDate: (NSDate *)date;
- (void) getHour: (NSInteger *)hourValuePointer
minute: (NSInteger *)minuteValuePointer
second: (NSInteger *)secondValuePointer
nanosecond: (NSInteger *)nanosecondValuePointer
fromDate: (NSDate *)date;
- (void) getEra: (NSInteger *)eraValuePointer 
yearForWeekOfYear: (NSInteger *)yearValuePointer 
weekOfYear: (NSInteger *)weekValuePointer 
weekday: (NSInteger *)weekdayValuePointer 
fromDate: (NSDate *)date;
#endif
```
> Add 10.9 methods for getEra:..., getHour:... etc

- Headers/Foundation/NSProgress.h
- Source/NSProgress.m
- Tests/base/NSProgress/basic.m
Matches Apple implementation.
Also removes duplicate release of `_userInfo` in dealloc, and extends NSProgress test to check user info.
> Add userInfo accessor to NSProgress

- ChangeLog
- Tests/base/GSTLS/basic.m
- Tests/base/NSData/additions.m
- Tests/base/NSProgress/basic.m
- Tests/base/NSString/tilde.m
- Fix GSTLS unit test
- NSData unit test
- Check for nil in NSData
- NSString unit test
- Fix NSProgress unit test
- Replace Objective-C string with cstring in PASS_EQUAL macros
- Fix UserInfo check by retrieving UTF8String
> GSTLS, NSData, NSString Unit Test Fixes on Windows MSVC

- Tests/base/NSNumberFormatter/basic10_4.m
It is not guaranteed by ICU that UNUM_NAN_SYMBOL is "NaN". On Windows, NaN has a negative signum and returns "-NaN".
> Mark notANumber test case as hopeful

- Tests/base/GSMime/general.m
This test fails when running on msys2, but succeeds when executed from cmd.exe. It passes in CI.
> Detect CRLF in GSMime tests

- Tests/base/NSPredicate/basic.m
Not sure why this didn’t cause a failure in recent builds, do failed builds not count as test failures?
```
--- Running tests in base/NSPredicate ---
Building basic
Building base/NSPredicate/basic.m
make debug=yes basic
Making all for test_tool basic...
Compiling file basic.m ...
basic.m: In function ‘main’:
basic.m:253:56: error: stray ‘@’ in program
253 |   p = [NSPredicate predicateWithFormat: @"self IN %@", @[@"yes"]];
|                                                        ^
basic.m:253:59: error: expected ‘:’ before ‘]’ token
253 |   p = [NSPredicate predicateWithFormat: @"self IN %@", @[@"yes"]];
|                                                           ^    ~
|                                                           :
basic.m:254:8: error: stray ‘@’ in program
254 |   a = …
```
> Fix NSPredicate test using GCC

- Documentation/HtmlNav/index.html
- Documentation/coding-standards.texi
- Documentation/manual/WorkingWithObjects.texi
The offline documentation is missing links to the manual and coding standards. 
This is due to errors in the texi files which prevent the make file to generate HTML versions and a broken link.
> fix missing links in generated documentation

- .github/scripts/dependencies.sh
- .github/workflows/main.yml
Various changes to modernize the CI and making it more reliable, mainly by using pre-built dependencies for the Windows MSVC targets instead of always building them ourselves (too much can go wrong in terms of servers being down etc.).
- update GitHub actions (fixes Node.js 12 deprecation warnings)
- separate Linux and Windows jobs
- Windows MSVC: use dependencies from pre-built release instead of building dependencies on every run (with option to build dependencies when using manual "Run Workflow", example run [here](https://github.com/gnustep/libs-base/actions/runs/3834875221/jobs/6527653656))
- Windows MSVC: set GitHub token when building dependencies to prevent GitHub rate limit errors
- remove installation of libkqueue-dev package (not used by libdispatch)
- update dependencies from …
> CI: various improvements

- .github/workflows/main.yml
- ChangeLog
- Headers/Foundation/NSURLSession.h
- Source/Additions/GSInsensitiveDictionary.m
- Source/Additions/GSMime.m
- Source/GSEasyHandle.m
- Source/GSHTTPURLProtocol.m
- Source/GSMultiHandle.h
- Source/GSMultiHandle.m
- Source/GSNativeProtocol.h
- Source/GSNativeProtocol.m
- Source/GSTimeoutSource.h
- Source/GSTimeoutSource.m
- Source/GSTransferState.h
- Source/GSTransferState.m
- Source/NSURLRequest.m
- Source/NSURLResponse.m
- Source/NSURLSession.m
- Tests/base/NSURLSession/test01.m
- Adds various missing APIs on NSURLSession (some of them stubs calling `-notImplemented:`)
- Fixed various memory management issues
- `-[GSEasyHandle resetTimer]` was referencing a destroyed object
- libdispatch objects were not being released
- GSHTTPURLProtocol was over-releasing an array object
- Fixed various cases where NSURLSession header fields were not being treated case-insensitive, because classes were accidentally using normal `NSDictionary` objects instead of `_GSMutableInsensitiveDictionary` e.g. when being copied.
> NSURLSession fixes and improvements

- Source/NSData.m
- Tests/base/NSData/base64.m
Don't call `NSZoneRealloc` with a length of 0, but free the zone and return an empty `NSData` buffer instead.
This pattern was observed when unarchiving Xib files.
> `[NSData initWithBase64EncodedString]`: Fix decoding of an empty string

- ChangeLog
- Source/NSOrderedSet.m
We found that the code marked as follows does not match the actual behavior on macOS:
> HACK ... MacOS-X seems to code differently if the coder is an actual instance of NSKeyedArchiver
This seems to have been copy-pasted from the NSSet implementation, but does not apply to NSOrderedSet, making NSOrderedSet instances encoded with GNUstep incompatible with Apple platforms.
> NSOrderedSet: Fix keyed encoding to match Apple platforms

- Tests/base/NSURL/basic.m
httpbin.org has lately been unreliable, leading to spurious test failures like this on CI:
```
Failed test:     (2023-05-05 11:35:31.207 +0000) basic.m:51 ... Can load a page from httpbin.org
Failed test:     (2023-05-05 11:35:31.207 +0000) basic.m:54 ... Status of load is 200 for httpbin.org
```
> Change NSURL tests to use example.com

- config/config.initialize.m
Was failing due to:
```
In file included from conftest.c:97:
././config/config.initialize.m:83:25: error: incompatible function pointer types passing 'void *(void *)' to parameter of type '_beginthreadex_proc_type' (aka 'unsigned int (*)(void *)') [-Wincompatible-function-pointer-types]
if (CREATE_THREAD(t1, test, 0))
^~~~
././config/config.initialize.m:12:27: note: expanded from macro 'CREATE_THREAD'
_beginthreadex(NULL, 0, start, arg, 0, &threadId) != 0
^~~~~
C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\process.h:99:40: note: passing argument to parameter '_StartAddress' here
_In_      _beginthreadex_proc_type _StartAddress,
^
```
This was causing the following incorrect configure output building with libobjc2 on Windows:
```
configure: WARNING: Your ObjectiveC …
```
> Fix runtime initialize config check on Windows

- ChangeLog
- Headers/Foundation/NSFileManager.h
- Source/NSFileManager.m
This is a shallow fix for possible crashes when concurrently calling various APIs which internally use `+[NSFileManager defaultManager]`, such as `-[NSData writeToFile:options:error:]`.
Guards access to the `_lastError` instance variable with a lock, so that concurrent invocations of NSFileManager methods modifying the variable will not e.g. cause over-release of objects.
This is mainly meant to fix crashes when no error occurs. Note however that the actual error handling is not made thread safe with this fix, i.e. if an error occurs while another method is concurrently using the file manager APIs there can still be crashes and incorrect control flow. I see two ways to fix this properly:
1. Replace the `_lastError` instance variable with local error variables that are passed through the …
> Improve NSFileManager thread safety

- ChangeLog
- Source/NSURL.m
- Tests/base/NSURL/basic.m
Fixes issue on Windows where initializing NSURL with an [UNC path](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths) like `\\server\path\xxx\` and getting back its path adds an extra leading forward slash:
```objc
NSURL *url = [NSURL fileURLWithPath:@"\\\\path\\to\\test.txt"];
NSLog(@"url: %@", url); // => file:///%5C%5Cpath%5Cto%5Ctest.txt
NSLog(@"path: %@", url.path); // => /\\path\to\test.txt (extra forward slash)
```
> Fix NSURL path on Windows for UNC paths

- ChangeLog
- Source/NSData.m
Initializing NSData with a file URL was using `-[NSURL resourceDataUsingCache:]` to load the file, which as a side effect caused the file data to be cached in memory. This is probably not desired behavior and caused very large memory growths in our application, and doesn’t match the behavior on Apple platforms.
> Fix NSData initWithContentsOfURL: caching data of file URLs

- Source/Additions/NSURL+GNUstepBase.m
- Source/GSSocketStream.h
- Source/GSSocketStream.m
- Source/win32/NSStream.m
It was discovered during Keysight's testing of our local fork of GNUStep Master that IPv6 functionality wasn't working properly. While this Pull Request doesn't fix all areas of IPv6, it at least gets sockets properly sized for IPv6 addresses. Please feel free to reach out to me with any questions or comments. If I missed anything I will happily provide it.
> Initial commit of updated IPv6

- ChangeLog
- Headers/Foundation/NSNumberFormatter.h
- Source/NSNumberFormatter.m
Not sure why they were defined as NSDecimalNumber, but in current Apple headers they are [defined as NSNumber](https://developer.apple.com/documentation/foundation/nsnumberformatter/1417228-minimum).
As far as I can tell these properties are not currently used in any implementations.
> Change NSNumberFormatter minimum/maximum properties type

- Source/Additions/NSURL+GNUstepBase.m
- Source/GSSocketStream.h
- Source/GSSocketStream.m
- Source/win32/NSStream.m
Reverts gnustep/libs-base#307
Oops ...I was wrong to do that.
> Revert "Initial commit of updated IPv6"

- Source/NSConcreteHashTable.m
- Source/NSConcretePointerFunctions.h
- Source/NSConcretePointerFunctions.m
- Source/NSPointerArray.m
This does not fix all the issues that were reported. At least it tries to sort out the bitfield access to the memory and personality options on pointer functions.
> Try to address issue of treating pointer function values as bitfield

- INSTALL
This is only a small patch that lifts libxslt, which is used in NSXMLDocument for xslt parsing, from OPTIONAL to RECOMMENDED, as a gnustep-base installation without libxslt would introduce inconsistency. The method objectByApplyingXSLT:arguments:error: (Available since Mac OS X 10.4) would just return nil if gnustep-base was compiled without libxslt support.
Additionally, libavahi for mDNS discovery, used in NSNetService (https://developer.apple.com/documentation/foundation/nsnetservice), and zlib, used in GSFileHandle for file compression should be listed and marked as RECOMMENDED.
> INSTALL: Add libavahi and zlib as requirements

- Documentation/GNUmakefile
When building the gnustep-base documentation (Documentation/GNUmakefile) without installing the base library into a standard library load path, compilation with 'autogsdoc' fails, as it requires libgnustep-base.
The modified LD_LIBRARY_PATH in the GNUmakefile to address this problem is incorrect, thus preventing autogsdoc to find the shared library.
> Fix LD_LIBRARY_PATH in Documentation GNUmakefile

- Headers/Foundation/NSKeyValueObserving.h
- Source/NSKeyValueObserving.m
> Add removeObserver:forKeyPath:context: to implementation

- Source/NSLock.m
- Tests/base/NSLock/unbalancedUnlock.m
This is a basic solution to issue #316,  it is likely not the right one, but I am hoping this PR provides the right forum for discussing what is correct.   It is worth noting that macOS does not throw an exception when an unlock fails.
> Issue a warning instead of throwing an exception

- Headers/Foundation/NSException.h
Using `__builtin_setjmp` when compiling with Clang on MSYS2 will result in compiler warnings and runtime crashes.  It seems to work on GCC, though.
Compiler warning on Clang:
```
warning: incompatible pointer types passing 'jmp_buf' (aka 'struct _SETJMP_FLOAT128[16]') to parameter of type 'void **' [-Wincompatible-pointer-types]
NS_DURING
^~~~~~~~~
note: expanded from macro 'NS_DURING'
if (!setjmp(NSLocalHandler.jumpState)) {
^~~~~~~~~~~~~~~~~~~~~~~~
note: expanded from macro 'setjmp'
#define setjmp(X)       __builtin_setjmp(X)
^
1 warning generated.
```
> Win64: Only use `__builtin_setjmp`/`__builtin_longjmp` when compiling with GCC

- .gitignore
- ChangeLog
- Headers/Foundation/NSKeyValueObserving.h
- Source/NSKeyValueObserving.m
- Tests/base/KVC/mutable.m
Add new methods and some tests for KVO.
> Add removeObserver:fromObjectsAtIndexes:forKeyPath:context: method

- Source/NSDistributedNotificationCenter.m
`NSTask launchPathForTool: @"gdnc"];` can return `nil` when the tool is not found.  In this case, `[NSTask launchedTaskWithLaunchPath]` would raise a `NSInvalidArgumentException` with error message "NSTask - no launch path set" which is not very descriptive.
> NSDistributedNotificationCenter: Throw a descriptive exception when gdnc could not be found

- Source/NSRegularExpression.m
- Tests/base/NSRegularExpression/basic.m
When creating a NSRegularExpression object on macOS, the following error message is created.
```objective-c
NSRegularExpression *exp;
exp = [NSRegularExpression regularExpressionWithPattern:@"(abc" options:0 error:&error];
if (!exp) {
NSLog(@"%@", error);
}
```
```sh
2023-11-11 19:43:08.886 objc-boilerplate[7287:328207] Error Domain=NSCocoaErrorDomain Code=2048 "The value “(abc” is invalid." UserInfo={NSInvalidValue=(abc}
```
On GNUstep we did not populate the error value.
Additionally, we did not check nil values:
```objective-c
NSRegularExpression *exp;
exp = [NSRegularExpression regularExpressionWithPattern:nil options:0 error:&error];
```
```sh
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSRegularExpression …
```
> NSRegularExpression: Improved Error and Exception handling to match macOS behaviour

- Headers/Foundation/NSObject.h
- Source/NSObject.m
I have check libs-base and found no code that expects a return value from setVersion:
As the GNUstep implementation diverges from Foundation, we treat this as a bug.
> NSObject: Change return type of setVersion: from id to void

- ChangeLog
- Headers/Foundation/NSURLRequest.h
- Source/NSURLRequest.m
- Tests/base/NSURLRequest/basic.m
Calling `setValue:forHTTPHeaderField:` with a nil value deletes the header on Apple platforms.
> Support deleting NSMutableURLRequest headers

- Tests/base/NSCalendar/era.m
Currently, the `NSCalendar` tests fail (at least on musl-based Alpine Linux v3.18) in the file _Tests/NSCalendar/era.m_ if the locale is set to any non-English locale. For example, with
```
$ export LANG=sr_RS.UTF-8
```
the ICU function `udat_parse` used by `NSDateFormatter` returns 9 (`U_PARSE_ERROR`) when passed the string containing English language month name (`@"22 Nov 1969 08:15:00 Z"`), which makes the tests fail.
This patch explicitly sets the `NSDateFormatter` locale in _Tests/NSCalendar/era.m_ to `en_US`.
Solves part of the issues in https://github.com/gnustep/libs-base/issues/356.
> Tests/base/NSCalendar/era.m: Fix testing with non-English locale

- Headers/GNUstepBase/GSVersionMacros.h
The GCC compiler will automatically export all symbols on MinGW, but this is not the case for clang.  Add the `__declspec` attributes when compiling with clang on MinGW.
> MinGW: Add dllimport/dllexport attributes when compiling with clang

- ChangeLog
- Headers/Foundation/NSProcessInfo.h
- Source/NSProcessInfo.m
Fixes NSLocale and NSTimeZone on Android.
Also adds another public initialization method to allow users to take control over initialization arguments.
> Initialize Android process with current locale and system time zone

- .github/scripts/dependencies.sh
- .github/workflows/main.yml
- Tests/GNUmakefile
libobjc2 now supports msys2/mingw64 and is part of the msys2 package repositories, so it's easier to add a CI job which uses that environment.
I had to make one minor change in `Tests/GNUMakefile` to avoid passing a `-rpath` flag on mingw.
The check for thread-safe +initialize in runtime will fail, but I believe #373 fixes that.
> Add CI leg for msys2/mingw64 using libobjc2 + gnustep-2.0 ABI

- .gitignore
- Source/GNUmakefile
- Source/gnustep-base.pc.in
- configure
- configure.ac
This PR updates the libs-base build process to generate a `gnustep-base.pc` file which is installed in `/lib/pkgconfig` and contains the GNUstep base version number, the libraries to link (equivalent to `gnustep-config --base-libs`) with and the C flags to use (equivalent to `gnustep-config --objc-flags`).
This can be useful when linking with libs-base in projects which don't use the GNUstep build system.
Sample output is:
```
Name: gnustep-base
Description: The GNUstep Base Library is a library of general-purpose, non-graphical Objective C objects.
Version: 1.29.0
Libs: -fuse-ld=lld -L/usr/local/lib64 -lstdc++ -pthread -fexceptions -rdynamic -fobjc-runtime=gnustep-2.0 -fblocks -L/home/vagrant/GNUstep/Library/Libraries -L/usr/local/lib -lgnustep-base -lpthread -lobjc -lm
Cflags:  -MMD -MP …
```
> Generate pkg-config configuration file for libs-base

- Tests/base/NSURL/basic.m
http://example.com/silly-file-name is currently returning 500 instead of 404, breaking tests.  Use https://gnustep.github.io instead.
> Tests/base/NSURL/basic.m: Use https://gnustep.github.io instead of http://example.com

- Source/GNUmakefile
- Source/NSNetServices.m
Always compile `NSNetService` and `NSNetServiceBrowser`, but have their `intialize` method throw an exception if libavahi and mDNS are unavailable.
This:
- Results in a clear error message if code which was compiled agains a copy of GNUstep with avahi/mDNS support runs on a copy of GNUstep which doesn't have avahi/mDNS support.
- Avoids code which uses `NSNetService` or `NSNetServiceBrowser` to successfully compile (because the classes are defined in the header) but then failing to link (because there is no implementation for these classes).
> NSNetService and NSNetServiceBrowser: Throw runtime exceptions

- Headers/GNUstepBase/GSVersionMacros.h
Most Linux distributions and MSYS2 include a version of BlocksRuntime which includes the `Block.h` header, e.g.:
- https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-libblocksruntime?repo=ucrt64
- https://packages.ubuntu.com/kinetic/amd64/libblocksruntime-dev/filelist
So it's likely you will want to include `Block.h` when compiling libs-base using clang on these platforms (assuming you're still on the GNU objc runtime).
Alternatively, I can update the ifdef to be `defined(__APPLE__) && defined(__clang__)` or `defined(__llvm__)`, or reverse the order of #if statments so that `objc/blocks_runtime.h` gets preference
> Use `__has_include` to choose between <Block.h> and <objc/blocks_runtime.h>

- ChangeLog
- Source/NSObject.m
See https://github.com/gnustep/libobjc2/pull/268, requires the upcoming Clang 18 (but doesn't hurt when using older releases).
It’s not clear to me why `_ARCCompliantRetainRelease` was guarded by `GS_ARC_COMPATIBLE` instead of the more fine-grained `OBJC_CAP_ARC`. The latter seems to also be used in other places (like in `NSAllocateObject`) as a kind of general check for libobjc2 availability, so I used it here as well and removed the former as it’s no longer used. Let me know if that doesn’t make sense.
We should probably also update Make to default to libobjc2 2.2 instead of 2.0.
> Add +[NSObject _TrivialAllocInit] to enable fast-path alloc / init methods with libobjc2 2.2

- Source/NSTimeZone.m
- Tests/base/NSTimeZone/use.m
We cannot use raw fopen, fscanf, etc. to access Assets on Android.
A higher-level API like +[NSString stringWithContentsOfFile:encoding:error:] should be used instead.
> Refactor +[NSTimeZone timeZoneArray] to use NSString instead of raw FDs

- Source/GSEasyHandle.m
- Source/GSMultiHandle.m
When connecting to an IPv6 socket fails, curl easy will return `CURLE_COULDNT_CONNECT`.  GNUstep currently maps `easyCode == CURLE_COULDNT_CONNECT && failureErrno == ETIMEDOUT` to `NSURLErrorTimedOut`, in all other scenarios `CURLE_COULDNT_CONNECT` is not handled.
This would cause the `NSURLSession/test01` to fail on (certain) systems with IPv6 enabled.
This PR maps all other values of `CURLE_COULDNT_CONNECT` to `NSURLErrorCannotConnectToHost`.
Additionally, it also stores the value of `easyCode` in the `NSUnderlyingErrorKey` to make troubleshooting (slightly) easier.
> Map `CURLE_COULDNT_CONNECT` to `NSURLErrorCannotConnectToHost`

- Headers/GNUstepBase/config.h.in
- configure
- configure.ac
Commit 4515e4a28b63ccd3e715cb21736e95242d671843 introduced a `AC_CHECK_LIB(sframe, sframe_decode)` in `configure.ac`. 
This causes libs-base to take a hard dependency on `libsframe`; `AC_CHECK_LIB` will prepend `lsframe` to LIBS even if the library is not found.  This results in a build failure on systems that don't have libsframe installed (and on which libsframe isn't available).  For example, libsframe is not available on Enterprise Linux (e.g. Rocky Linux).
This PR slightly modifies the original commit by using `AC_SEARCH_LIBS` making the library optional.
> Use AC_SEARCH_LIBS instead of AC_CHECK_LIB for sframe

- .github/workflows/main.yml
This build has been broken for a while, and I'm going to assume most users are on the 2.0 ABI by now.
> Remove Ubuntu x64 Clang gnustep-1.9 build leg

- Headers/GNUstepBase/config.h.in
- Source/NSThread.m
- Tests/base/NSThread/name.m
- configure
- configure.ac
Implements support for -[NSThread setName:] on win32. I am using `GetThreadDescription` and `SetThreadDescription` from `processthreadsapi.h`. This API was introduced in Windows 10 Redstone 1. Here is an overview of setting a thread name in native code: https://learn.microsoft.com/en-us/visualstudio/debugger/how-to-set-a-thread-name-in-native-code?view=vs-2022.
The test currently only checks correct behaviour on Windows, as I do not know how to reconfigure `configure.ac`. `autoreconf -vi` results in an erroneous `configure` script on Debian. @rfm how do you reconfigure autoconf in gnustep-base?
```objc
#import <Foundation/Foundation.h>
#import <pthread.h>
int main() {
@autoreleasepool {
pthread_setname_np("Hello World");
NSLog(@"Current Thread: %@", [[NSThread currentThread] name]); …
```
> Add support for -[NSThread setName:] on win32 and fix inconsistency in API behaviour

- .github/scripts/dependencies.sh
- .github/workflows/main.yml
4515e4a28b63ccd3e715cb21736e95242d671843 inadvertently broke building libs-base on Enterprise Linux (e.g. Rocky Linux).  #389 fixes the build, and this PR adds a CI job for Rocky Linux 9, hopefully helping us catch these errors when a PR for such changes gets raised.
It:
- Runs the Ubuntu 22.04 and Rocky Linux 9 jobs in a container
- Accounts for the lib/lib64 difference between Ubuntu & Rocky Linux
#389 and #388 are required to make this build succeed.
> Add a CI job for Rocky Linux 9

- Headers/Foundation/NSNotification.h
- Source/NSNotificationCenter.m
This modifies the NotificationCenter class to do the following:
- add an ivar to the class for an array to hold observers that need to be released when they are removed
- adds an observer to that array if the observer is of class GSNotificationObserver
- upon removing an observer, check if it is in that array, if so remove it from the array and release it.
This replaces the previous implementation which checked the class of the observer as it was being removed, which would cause a crash if the observer had been deallocated.
> NotificationCenter removeObserver

- .github/workflows/main.yml
actions/upload-artifact@v3 is scheduled for deprecation on November 30, 2024, so upgrade to v4.
Also hardcode the paths to `source/config.log` and `source/Tests/tests.log`, for some reason test logs weren't always captured and this fixes that.
> Use actions/upload-artifact@v4

- Headers/GNUstepBase/config.h.in
- Source/NSString.m
- Tests/base/NSURLConnection/test02.m
- configure
- configure.ac
Fixes building with the Windows-bundled ICU libraries (was broken with #370).
This wasn’t caught by CI because it’s still using Windows 2019 agents which don’t have the ICU library. I’ll open a separate PR to update this.
> Fix NSString ICU includes for Windows

- ChangeLog
- Source/NSXMLElement.m
- Source/NSXMLNode.m
- Tests/base/NSXMLElement/attributes.m
- Tests/base/NSXMLNode/xpath.m
Fix execute_xpath() to return an NSError when expression can't be evaluated; Remove previous attributes when setting attributes; Add related tests
> Two small xml fixes

- configure
- configure.ac
This caused errors when trying to run ./configure outside of the libs-base directory (to do out-of-tree builds).
Originally submitted as #371, which was closed without merging.
> Use absolute paths in ./configure

- Source/GSFileHandle.m
`fstat()` on UNIX isn't guaranteed to always succeed, even if the file handle is valid. Special files may or may not support `fstat()` in the kernel.
(For context, I'm working on a Vulkan application. Vulkan has facilities to send certain objects across processes by representing the objects as file descriptors. These file descriptors still need to be `close()`d, which makes them good candidates for wrapping an NSFileHandle around them, but they do not support `fstat()`. I'm creating multiple of these each frame in the application, which means the line "unable to get status of descriptor" appears very often in the terminal while my application is running.)
> -[NSFileHandle initWithFileDescriptor:] logs a message each time fstat() doesn't succeed on UNIX

- ChangeLog
- Headers/Foundation/NSFileManager.h
- MISSING
- Source/NSFileManager.m
This behaves like NSSearchPathForDirectoriesInDomains (at least, superficially. Not sure if Apple's implementation has some special behavior on top that their documentation doesn't mention.)
The documentation comment is copied from NSSearchPathForDirectoriesInDomains.
> Implement -[NSFileManager URLsForDirectory:inDomains:]

- Source/GSArray.m
- Source/NSArray.m
- Source/NSKeyValueMutableArray.m
- Tests/base/NSMutableArray/general.m
Updates the `-[NSMutableArray removeLastObject]` implementation to avoid raising an exception if the array is already empty. 
This brings the behavior of `-[NSMutableArray removeLastObject]` inline with the Apple implementation, improving compatibility for code bases which use both GNUStep and Apple objc/Foundation implementations.
RE: https://github.com/gnustep/libs-base/issues/432
> Update `-[NSMutableArray removeLastObject]`

- .github/workflows/main.yml
MSYS2 is slowly phasing out 32-bit support and removed gcc-objc as part of the 14.1.0 update. If someone is interested in keeping 32-bit support in CI, self-build binaries must be supplied.
> Remove MinGW 32-bit CI

- ChangeLog
- Source/NSThread.m
Android's pthread_setschedparam is currently broken, as it checks if the priority is in the range of the system's min and max priorities. The interval bounds are queried with `sched_get_priority_min`, and `sched_get_priority_max` which just return 0, regardless of the specified scheduling policy.
The solution is to use `setpriority` to set the thread priority. This is possible because on Linux, it is not a per-process setting as specified by POSIX but a per-thread setting (See the `Bugs` section in `setpriority`).
> NSThread: Fix `threadPriority` and `setThreadPriority:` on Android by using `setpriority` instead of pthread

- Source/NSProcessInfo.m
- Source/common.h
We have to discuss what should happen when a JNI call fails early during process initialisation. This should result in an abort IMO, as the environment is somehow corrupted.
> Add Branch Prediction Macros and Error checks in Android Initialisation

- ChangeLog
- Headers/Foundation/NSThread.h
- Source/NSString.m
- Source/NSThread.m
Apple's CoreFoundation caches a `UCollator` instance for a language in TSD. It turns out that instantiation of collators is a very expensive operation. Reusing existing collators greatly improves runtime when repeatedly comparing strings (i.e. when sorting).
Here are some selected benchmarks to validate the collator optimisation and the KVC optimisation from #445.
I've exported the titles of a large media libraries (~70000 songs) for the following micro benchmarks.
Benchmarks were performed on an AMD Ryzen 7 5700G (Freq. scaling disabled), 16GB of DDR4 RAM, Fedora 40.
```sh
Run on (16 X 400 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x8)
L1 Instruction 32 KiB (x8)
L2 Unified 512 KiB (x8)
L3 Unified 16384 KiB (x1)
```
```cpp
static void …
```
> NSString: Cache ICU collator in thread-local storage

- Headers/Foundation/NSKeyValueObserving.h
tinkering with KVO, ChatGPT told me to implement observeValueForKeyPath: ... alike:
```
- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary<NSKeyValueChangeKey,id> *)change context:(void *)context {
```
Instead of replacing with NSString *, this tiny change allows me to do as advised.
Documented here:
https://developer.apple.com/documentation/foundation/nskeyvaluechangekey?language=objc
> Add typedef NSKeyValueChangeKey to NSKeyValueObserving.h

- Headers/Foundation/NSURLError.h
https://web.archive.org/web/20131113010445/https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Miscellaneous/Foundation_Constants/Reference/reference.html
> Add some missing NSURLErrorDomain constants, as described here:

- ChangeLog
- Headers/Foundation/NSByteOrder.h
- Headers/Foundation/NSInvocation.h
- Headers/Foundation/NSValue.h
- MISSING
- Source/GSConcreteValue.m
- Source/GSConcreteValueTemplate.m
- Source/NSValue.m
- Source/typeEncodingHelper.h
- Tests/base/KVC/type_encoding.m
NSValueGeometryExtensions was missing 2 functions, I added them, they work, but it’s possible that GSEdgeInsets does not have the correct description, but I can’t check what it should be, but essentially it does what it should.
> Add EdgeInsets missing function in value

- Source/GSFFIInvocation.m
- Tests/base/NSKVOSupport/proxy.m
When observing properties via a proxy object, all messages are encapsulated into an NSInvocation object.
From the example in #472, the following messages are forwarded to the underlying object:
- `addObserver:forKeyPath:options:context:`
- `removeObserver:forKeyPath:options:context:`
- `setName:`
When adding a observer for the first time (assuming that there are no associated objects),  a hidden subclass is created and attached (ISA changes) to the TObject instance.  `setName:` is then swizzled and added to the hidden subclass.
The current invocation mechanism uses APIs that skip over hidden classes during method lookup, resulting in the original IMP being called instead of the swizzled one.
This is documented in NSKVOSwizzling: https://github.com/gnustep/libs-base/blob/9cdb4f98ba77165cfa8 …
> GSFFIInvocation: Use `objc_msg_lookup` in -invokeWithTarget: to avoid skipping hidden classes 

- Source/NSKVOInternal.h
- Source/NSKVOSupport.m
- Source/NSKVOSwizzling.m
- Tests/base/NSKVOSupport/proxy.m
While not explicitly allowed, observing an object from a stand-in, a NSProxy subclass, works on macOS.
As outlined in #472, we are currently facing two issues preventing this to work:
1. Class methods are not forwarded by design
2. KVO currently tries to swizzle the stand-in, and not the underlying object
I've tried not to introduce additional overhead, and implemented `- _underlyingClass` in a NSObject and NSProxy category.
The implementation in NSObject simply returns `[self class]`, while -[NSProxy _underlyingClass] calls `[self valueForKey: @"class"]` to retrieve the underlying class.
When swizzling, we check for a mismatch between `-class` and `-_underlyingClass`.
> Key-Value Observing: Add support for observing through a proxy

- Headers/Foundation/NSCalendar.h
- Headers/Foundation/NSObjCRuntime.h
- Source/NSCoder.m
- Source/NSUnarchiver.m
Fixes #494.
I’m guessing this is an ABI breaking change, not sure how this should be handled.
> Fix NSNotFound definition to use NSInteger type

- ChangeLog
- Headers/Foundation/NSURLHandle.h
- Source/GSHTTPURLHandle.m
- Source/NSURLProtocol.m
- Source/externs.m
Fixes `Authorization` header generation to include the query parameters (if present). 
This brings the implementation inline with MacOS, and fixes digest auth with certain picky services.
Tested these changes against the IC Realtime ORB camera I was having issues with in https://github.com/gnustep/libs-base/issues/497, and our application successfully authenticated with this fix.
> Fix `Authorization` header generation

- Headers/Foundation/NSCalendar.h
- Headers/Foundation/NSCalendarDate.h
- Headers/Foundation/NSCharacterSet.h
- Headers/Foundation/NSData.h
- Headers/Foundation/NSError.h
- Headers/Foundation/NSIndexPath.h
- Headers/Foundation/NSPointerArray.h
- Headers/Foundation/NSPointerFunctions.h
- Source/NSCalendar.m
- Source/NSCharacterSet.m
These changes match Apple headers and the actual implementations, i.e. `instancetype` is used if the implementation calls `[self alloc]`, and otherwise the actual type is used.
This enables using dot notation on the returned objects (e.g. `[NSData dataWithContentsOfURL:url].length`), which the compiler will not accept with an `id` return type.
> Use instancetype or actual type as initializer return types

- Source/NSBundle.m
The conversion between BCP 47 language tags and
the old-style language names ('English', 'German', etc) is quite complex, mapping ISO 639-1 language tags to the old-style names, and the result back to ISO 639-1 (-ish).
The ISO 639-1 tag for spanish 'es' maps to 'Spanish', which in turn maps back to 'sp'. The original input is not added to the list of possible names for 'lproj' folders.
We fix this by operating on the official input, when splitting language, variant, and region. The "mapped" tag is always added just to keep 'sp.lproj' working.
> NSBundle: fix es.lproj path not generated

- Source/NSTimeZone.m
tz.StandardName is not always available, does not represent the raw timezone key from the registry. It appears that ucal_getTimeZoneIDForWindowsID maps the registry key to a compatible IANA time zone.
The dotnet and flutter implementations also use
GetDynamicTimeZoneInformation and use TimeZoneKeyName.
Here is an example for Asia/Singapore:
StandardTime = Malay Peninsula Standard Time
TimeZoneKeyName = Singapore Standard Time
StandardTime is not registered in the IANA database.
> NSTimeZone: Use GetDynamicTimeZoneInformation

- Headers/Foundation/NSJSONSerialization.h
- Source/NSJSONSerialization.m
- Tests/base/NSJSONSerialization/sorted.m
This PR implements the option NSJSONWritingSortedKeys, which sorts keys of a JSON dictionary in lexicographic order.
> NSJSONSerialization: Implement NSJSONWritingSortedKeys

- Headers/Foundation/NSData.h
- Source/NSData.m
- Tests/base/NSData/errors.m
Instead of printing out a warning, the underlying file reading function creates proper NSError objects, that are returned to the user.
The following initializers were implemented:
-[NSData initWithContentsOfFile:options:error:]
-[NSData initWithContentsOfURL:options:error:]
+[NSData dataWithContentsOfFile:options:error:]
+[NSData dataWithContentsOfURL:options:error:]
Additionally NSDataReadingOptions was added to NSData.h. Please note that NSDataReadingMappedIfSafe, and NSDataReadingMappedAlways currently have no effect, and need to be implemented properly.
> NSData: Improve error handling and new initialiser

- Headers/Foundation/NSFileHandle.h
- Source/GSFileHandle.m
- Source/NSFileHandle.m
- Tests/base/NSFileHandle/reading.m
- Tests/base/NSString/basic.m
As part of Apple's ongoing improvements for interoperability between Swift and Foundation, a significant part of NSFileHandle was deprecated in favour of methods that write out errors.
This pull request implements the following new APIs:
```objc
- (BOOL) writeData: (NSData *) data 
error: (NSError **) error;
- (NSData *) readDataUpToLength: (NSUInteger) length 
error: (NSError **) error;
- (NSData *) readDataToEndOfFileAndReturnError: (NSError **) error;
```
Refactors GSFileHandle to return errors in private helper methods, and fixes some declaration differences between Apple's Foundation and GNUstep.
> feat(NSFileHandle): Add new APIs with error handling, and refactor GSFileHandle

- Headers/Foundation/NSDebug.h
Fixes #513. I don't know if this is the right solution to the problem, since I don't know why the declarations were hidden when NDEBUG was defined in the first place.
> expose declarations in NSDebug.h even when NDEBUG is defined

- configure
- configure.ac
This ensures consistency within the configure script, and  allows users to override the exact version of pkg-config which is being used.  This allows for the use of  alternatives, such as pkgconf.
> Use $PKG_CONFIG to invoke pkg-config

- Source/win32/GSFileHandle.m
I forgot to add some methods in the Windows-specific version of `GSFileHandle` in #510 . Here is the fix.
> fix(win32/GSFileHandle): Add missing methods

- .github/workflows/main.yml
- Headers/GNUstepBase/config.h.in
- Source/NSURLSessionConfiguration.m
- Source/NSURLSessionTask.m
- configure
- configure.ac
RHEL 8 (and other members of the RHEL family, such as Rocky Linux 8) ship with libcurl 7.61.
With the latest release, curl was made a hard requirement when compiling with the ng runtime, and the minimum version was bumped to 7.66.  This means support for RHEL 8 was dropped when using the ng runtime.
This PR:
1. Adds a CI job which tests on Rocky Linux 8
2. Relaxes the curl requirement from 7.66 to 7.61
The changes look fairly minimal, and increase backward compatibility, so I hope this is worth the effort.
> Add support for Rocky Linux 8 / libcurl 7.61

- config/pathtls.m4
- config/pathxml.m4
- config/procfs.m4
- configure
- configure.ac
As we are it, clean up all help messages with AS_HELP_STRING
> cast to iconv_t which is correct according to declaration and get rid of warnings

- Source/GSFormat.m
Should be safe from GCC 4.5 and optionally with -std=c99 from 3.0, We dropped 2.95 long ago.
> make va_copy work on muslc and gcc 14
